### PR TITLE
Fixed database seeders

### PR DESCRIPTION
**Pull request by lolsokje**
Without these fixes, seeding the database doesn't work as the `paymentgateways` table is renamed to `payment_gateways` at some point, while the seeder remained untouched.

### CODE REVIEW

**Review by ajithjojo — APPROVED** [review]
Thanks

**Comment by ajithjojo** [comment]
Please make a pull req again , so i can marge it ..

**Comment by lolsokje** [comment]
@ajithjojo does anything need to be fixed or is there another reason you reverted the changes?

**Comment by ajithjojo** [comment]
actually i merged another update after merging ur's that override your update..

**Comment by ajithjojo** [comment]
please submit again

**Pull request merged**
