### PR TITLE
Feature: Rename database table columns and adjust their data types

### PR DESCRIPTION
**Pull request by MeiKatz**
This pull request unifies a lot of database table columns, either by their name or by their data type, mostly by both cases. In a follow-up pull request I will introduce a currency column for all money related tables, an `default_currency` option in settings and for each client, and will make use of a [money handling package](https://github.com/moneyphp/money).

Also the table `invoices` will be split into `invoices`, `offers`, and `subscriptions` (for recurring invoices).

### CODE REVIEW

**Comment by MeiKatz** [comment]
@ajithjojo are you currently very busy or are there other reasons why this pull request is not merged yet?

**Comment by ajithjojo** [comment]
hey buddy .. i was busy .. and i havent got time to check on .. am merging now

**Comment by MeiKatz** [comment]
Alright. Maybe we need some way to directly communicate with each other to exchange information like this. Any idea?

**Comment by ajithjojo** [comment]
@MeiKatz  we can use whatsapp ,  or any other communication methods ..  +91 8129 505560

**Pull request merged**
