### PR TITLE
Fix: normalize class names

### PR DESCRIPTION
**Pull request by MeiKatz**
It's just a first step but I used the normal Laravel / PHP convention for class names (camel case and singular). Also I fixed a name typo: it is not "payment recepit" but "payment receipt".

### CODE REVIEW

**Comment by ajithjojo** [comment]
Hey , Thanks for your submssion. 
i am reviewing your code, have you run this on your local env ? 
when i run your code i am getting may errors , bcoz of typo

**Comment by MeiKatz** [comment]
Actually I haven't run it at all yet, just did static code analysing. But I will check it in the next few hours.

**Comment by ajithjojo** [comment]
just run it, you can see the errors from dashboard, we have to fix that

**Comment by MeiKatz** [comment]
Okay, I run it locally and fixed the errors. Should work now. Also: there has to be a solution for the missing logo and company name at start. Without a seed or a placeholder you get the error that `$settings` is undefined.

**Comment by ajithjojo** [comment]
Thank you

**Comment by MeiKatz** [comment]
@ajithjojo Do you have any plans when you will merge any of the pull requests? Currently I have some time and want to get some work done in this project but for now any change blocks other changes.

**Comment by ajithjojo** [comment]
image
Please fix these errors .. please run the code on your PC , bcoz after we login i am getting this error ..

**Comment by MeiKatz** [comment]
Did you run the migrations?

**Comment by ajithjojo** [comment]
no .. sorry , i just did .. now its working , merging now

**Pull request merged**
