### PR TITLE
Refactor admin controllers

### PR DESCRIPTION
**Pull request by MeiKatz**
I refactored all your controllers, views and routes related to your admin functionality. They are now more readable, more maitainable and much cleaner. They need a lot more refactoring related to the bunch of code in the action methods, but for now it's a good start to get off.

### CODE REVIEW

**Comment by ajithjojo** [comment]
Thank you for your efforts. I really appreciate your work. I will take a look in the morning and merge with Master.

**Comment by MeiKatz** [comment]
Just a note from my side: it would be better if you merge my other pull request first, then I adapt the class name changes from there and then you can merge this pull request.

**Comment by ajithjojo** [comment]
hey buddy .. i would love to accept your pull .. but when i testing am getting errors .. 
image

**Comment by MeiKatz** [comment]
Yeah, I haven't checked this pull request because of this:

> Just a note from my side: it would be better if you merge my other pull request first, then I adapt the class name changes from there and then you can merge this pull request.

I the other pull request is merged I will merge it into this pull request and resolve the errors at once, alright?

**Pull request merged**
